Repository hypertrons/hypertrons-crx, pull requests merged in 2021-06, with the labels that each got.

#134 feat: add node click event for GraphinWrapper
  package-lock.json
  package.json
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/api/developer.ts
  src/api/repo.ts
  src/components/ExceptionPage/ErrorMessageBar.tsx
  src/components/ExceptionPage/ErrorPage.tsx
  src/components/Graph/Graph.tsx
  src/components/Graph/Graphin/index.tsx
  src/components/OptionsPage/index.tsx
  src/constant.ts
  src/global.d.ts
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/Perceptor.tsx
  src/pages/Content/PerceptorBase.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/pages/Content/types.d.ts
  src/utils/logger.tsx
  src/utils/request.ts
  src/utils/settings.ts
  src/utils/utils.ts
  utils/build.js
  utils/env.js
  utils/watch.js
  webpack.config.js
Labels: pull/approved

#135 feat: update nodeSize mapping methord
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/assets/img/antv.png
  src/assets/img/echarts.png
  src/assets/img/main.png
  src/components/Graph/Echarts/index.tsx
  src/components/Graph/Graph.tsx
  src/components/OptionsPage/index.tsx
  src/components/PopupPage/index.tsx
  src/constant.ts
  src/utils/utils.ts
Labels: pull/approved

#138 refactor: update update_information.json
  publish/update_information.json
Labels: kind/enhancement, pull/approved

#139 fix: wrong update url bug
  package.json
  src/components/OptionsPage/index.tsx
  src/services/common.ts
Labels: kind/bug, pull/approved

#140 docs: update README
  README.md
  README.zh-CN.md
  assets/crx-demo-d1.png
  assets/crx-demo-d2.png
  assets/crx-demo-p1.png
  assets/crx-demo-p2.png
Labels: area/document, pull/approved

#146 fix: redundant clone bug
  src/pages/Content/PerceptorTab.tsx
Labels: kind/bug, pull/approved

#148 docs: add Chinese installation guide (just for Chrome) #136
  INSTALLATION.zh-CN.md
  assets/installation_p1.png
  assets/installation_p2.png
  assets/installation_p3.png
  assets/installation_p4.png
  assets/installation_p5.png
  assets/installation_p6.png
Labels: area/document, pull/approved

#149 feat: choose language manually
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/ExceptionPage/ErrorMessageBar.tsx
  src/components/ExceptionPage/ErrorPage.tsx
  src/components/Graph/Graph.tsx
  src/components/Graph/Graphin/index.tsx
  src/components/OptionsPage/index.tsx
  src/components/PopupPage/index.tsx
  src/pages/Background/index.ts
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/pages/Content/TeachingBubbleWrapper.tsx
  src/utils/settings.ts
  src/utils/utils.ts
Labels: pull/approved

#150 refactor: remove dark mode
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/Graph/Graph.tsx
  src/constant.ts
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectNetwork.tsx
Labels: kind/enhancement, pull/approved

#151 Create issue_template.md
  .github/issue_template.md
Labels: pull/approved

#152 feat: add loading to perceptor layout
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/ExceptionPage/ErrorMessageBar.tsx
  src/components/ExceptionPage/ErrorPage.tsx
  src/components/Graph/Graphin/index.tsx
  src/components/OptionsPage/index.tsx
  src/components/PopupPage/index.tsx
  src/pages/Background/index.ts
  src/pages/Content/PerceptorLayout.tsx
  src/pages/Content/TeachingBubbleWrapper.tsx
Labels: pull/approved

#153 fix: bug caused by pr 152
  src/pages/Content/PerceptorLayout.tsx
  src/pages/Content/ProjectNetwork.tsx
Labels: kind/bug, pull/approved

#154 fix: locale bug in options page
  src/components/OptionsPage/index.tsx
Labels: kind/bug, pull/approved

#159 feat: update the cloning process
  README.md
Labels: pull/approved

#157 refactor: add friendly notification if data not found
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/ExceptionPage/ErrorMessageBar.tsx
  src/components/ExceptionPage/ErrorPage.tsx
  src/components/Graph/Graph.tsx
  src/constant.ts
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/utils/request.ts
Labels: kind/enhancement, pull/approved

#160 refactor: remove default_locale in manifest
  src/components/OptionsPage/index.tsx
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
  src/manifest.json
  src/utils/utils.ts
Labels: kind/enhancement, pull/approved

#166 Typo fix in Issue_template
  .github/issue_template.md
Labels: pull/approved

#167 release v1.0.1
  publish/update_information.json
Labels: pull/approved

#168 fix: perceptor menu item bug
  src/pages/Content/PerceptorTab.tsx
Labels: kind/bug, pull/approved

#171 Doc: update README and installation guide
  INSTALLATION.md
  INSTALLATION.zh-CN.md
  README.md
  README.zh-CN.md
  assets/crx-demo-d1.png
  assets/crx-demo-d2.png
  assets/crx-demo-p1.png
  assets/crx-demo-p2.png
  assets/installation_p1.png
  assets/installation_p2.png
  assets/installation_p3.png
  assets/installation_p4.png
  assets/installation_p5.png
  assets/installation_p6.png
Labels: area/document, pull/approved

#173 feat: Distinguish the current node from other nodes
  src/components/Graph/Graph.tsx
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectNetwork.tsx
  webpack.config.js
Labels: pull/approved

#174 feat: change theme of options page
  package.json
  src/components/OptionsPage/index.css
  src/pages/Options/index.css
Labels: pull/approved

#176 fix: fix typo
  README.zh-CN.md
  src/components/OptionsPage/index.tsx
Labels: kind/bug, pull/approved

#185 Some typos fixed in docs and Data Item Link
  README.md
  src/pages/Content/PerceptorTab.tsx
Labels: area/document, pull/approved

#186 New Icon for Perceptor Tab
  src/pages/Content/PerceptorTab.tsx
Labels: pull/approved

#187 feat: add toggle for enable perceptor or not
  .gitignore
  src/components/OptionsPage/index.tsx
  src/components/PopupPage/index.tsx
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
  src/pages/Background/index.ts
  src/pages/Content/index.ts
  src/pages/Popup/index.css
  src/utils/settings.ts
Labels: pull/approved

#192 Added Token info to EN Installation Guide
  INSTALLATION.md
  assets/en/ex.png
  assets/en/mo.png
  assets/en/op.png
  assets/en/set.png
  package-lock.json
Labels: pull/approved
