Repository hypertrons/hypertrons-crx, pull requests merged in 2021-11, with the labels that each got.

#235 docs: update Hypertrons-crx to Hypercrx in src/manifest.json
  src/manifest.json
Labels: area/document, pull/approved

#240 fix: bug blocking build and release
  .github/workflows/build.yml
  src/components/DynamicRadar/Radar/Radar.tsx
Labels: kind/bug

#239 refactor: More accurate error message when data not found
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
Labels: kind/enhancement, kind/bug, pull/approved
