Repository hypertrons/hypertrons-crx, pull requests merged in 2021-04, with the labels that each got.

#82 feat: implement checking for updates
  src/assets/img/main.png
  src/components/OptionsPage/index.tsx
  src/components/PopupPage/index.tsx
  src/manifest.json
  src/mock/background.data.ts
  src/pages/Background/index.ts
  src/services/background.ts
  src/utils/settings.ts
  src/utils/utils.ts
Labels: pull/approved

#83 feat: notification & button for updates
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/OptionsPage/index.tsx
  src/mock/background.data.ts
  src/pages/Background/index.ts
  src/services/background.ts
  src/services/common.ts
  src/utils/metadata.ts
  src/utils/settings.ts
  src/utils/utils.ts
Labels: pull/approved

#87 Feat: add error page
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/api/index.ts
  src/components/ExceptionPage/index.tsx
  src/pages/Content/features/developer-network.tsx
  src/pages/Content/features/project-network.tsx
  src/utils/utils.ts
Labels: kind/bug, pull/approved

#89 Feat: add log mechanism
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/ExceptionPage/ErrorMessageBar.tsx
  src/pages/Content/features/developer-network.tsx
  src/pages/Content/features/index.tsx
  src/pages/Content/features/project-network.tsx
Labels: pull/approved

#84 feat: publish asserts to oss
  .github/workflows/build.yml
Labels: pull/approved

#90 refactor: upload publish information to oss
  .github/workflows/build.yml
  publish/update_information.json
Labels: kind/enhancement, pull/approved

#88 doc: add installation guide #85
  INSTALLATION.md
  README.md
Labels: area/document, pull/approved

#91 fix: avoid style pollution
  src/pages/Content/features/developer-network.css
  src/pages/Content/features/developer-network.tsx
  src/pages/Content/features/project-network.css
  src/pages/Content/features/project-network.tsx
  src/pages/Content/index.css
Labels: kind/bug, pull/approved

#92 fix: update project network
  src/pages/Content/features/developer-network.tsx
  src/pages/Content/features/index.tsx
  src/pages/Content/features/project-network.tsx
Labels: kind/bug, pull/approved

#93 Refactor: refactor content scripts and load remote config from repo file
  package-lock.json
  package.json
  src/api/github.ts
  src/components/PerceptorLayout/index.tsx
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/Perceptor.tsx
  src/pages/Content/PerceptorBase.tsx
  src/pages/Content/PerceptorLayout.tsx
  src/pages/Content/PerceptorTab.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/pages/Content/config-service.ts
  src/pages/Content/content.styles.css
  src/pages/Content/features/developer-network.tsx
  src/pages/Content/features/index.tsx
  src/pages/Content/features/perceptor-layout.tsx
  src/pages/Content/features/perceptor-tab.tsx
  src/pages/Content/index.css
  src/pages/Content/index.ts
  src/utils/settings.ts
  src/utils/utils.ts
  tsconfig.json
Labels: kind/enhancement, pull/approved

#94 feat: jump to certain url when user clicks update notification
  src/pages/Background/index.ts
  src/services/background.ts
  src/services/common.ts
  src/utils/metadata.ts
Labels: pull/approved

#96 fix: change update url
  src/components/OptionsPage/index.tsx
  src/pages/Background/index.ts
  src/services/background.ts
Labels: kind/bug, pull/approved

#97 feat: add Most Participated Repos & Active Developer Collaboration Network graph
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/api/index.ts
  src/components/Graph/GraphWithList.tsx
  src/components/Network/ForceNetwork.tsx
  src/global.d.ts
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/pages/Content/content.styles.css
  src/utils/utils.ts
Labels: pull/approved

#98 refactor: refactor IOC mechanism
  README.md
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/Perceptor.tsx
  src/pages/Content/PerceptorBase.tsx
  src/pages/Content/PerceptorLayout.tsx
  src/pages/Content/PerceptorTab.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/pages/Content/index.ts
  src/utils/utils.ts
Labels: kind/enhancement, pull/approved

#99 feat: support for github token
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/OptionsPage/index.tsx
  src/services/common.ts
  src/utils/metadata.ts
Labels: pull/approved

#100 feat: github token for popup page
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/api/github.ts
  src/components/OptionsPage/index.tsx
  src/components/PopupPage/index.tsx
Labels: pull/approved

#105 feat: introduce antv graph
  package.json
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/assets/img/antv.png
  src/assets/img/echarts.png
  src/components/Graph/GraphWithList.tsx
  src/components/OptionsPage/index.tsx
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/utils/settings.ts
  src/utils/utils.ts
  webpack.config.js
Labels: pull/approved

#106 [Refactor] Change OSS base URL into x-lab.info
  src/api/index.ts
  src/services/background.ts
Labels: kind/enhancement, pull/approved
