Repository hypertrons/hypertrons-crx, pull requests merged in 2021-05, with the labels that each got.

#109 feat:new ui&ux for project network
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/api/index.ts
  src/assets/img/charts.png
  src/components/Graph/GraphWithList.tsx
  src/manifest.json
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectBase.tsx
  src/pages/Content/content.styles.css
  src/services/background.ts
Labels: pull/approved

#111 Refactor: refactor API request
  .gitignore
  package-lock.json
  src/api/developer.ts
  src/api/index.ts
  src/api/repo.ts
  src/mock/developer.data.ts
  src/mock/project.data.ts
  src/mock/repo.data.ts
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/Perceptor.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/utils/request.ts
  utils/web-ext-profile/.gitkeep
Labels: kind/enhancement, pull/approved

#114 Refactor: refactor graph component
  src/api/developer.ts
  src/api/repo.ts
  src/components/Graph/Graph.tsx
  src/components/Graph/GraphWithList.tsx
  src/global.d.ts
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/Perceptor.tsx
  src/pages/Content/ProjectBase.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/utils/color.ts
  src/utils/number.ts
  src/utils/utils.ts
Labels: kind/enhancement, pull/approved

#115 feat:add teaching bubble for perceptor tab
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/PerceptorTab.tsx
  src/pages/Content/ProjectBase.tsx
  src/pages/Content/TeachingBubbleWrapper.tsx
Labels: pull/approved

#116 fix: modal too narrow when viewing networks
  src/pages/Content/content.styles.css
Labels: kind/bug, pull/approved

#119 feat: add dark mode, period selection and description for graph
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/Graph/Echarts/index.tsx
  src/components/Graph/Graph.tsx
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectBase.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/pages/Content/content.styles.css
  src/pages/Content/types.d.ts
  src/utils/request.ts
Labels: pull/approved

#120 feat: add notification for options page
  publish/notification.json
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/OptionsPage/index.tsx
  src/mock/background.data.ts
  src/pages/Background/index.ts
  src/pages/Content/TeachingBubbleWrapper.tsx
  src/services/background.ts
  src/utils/metadata.ts
Labels: pull/approved

#121 feat: add graphinWrapper and change position of developer network
  package-lock.json
  package.json
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/assets/img/charts.png
  src/components/Graph/Echarts/index.tsx
  src/components/Graph/Graph.tsx
  src/components/Graph/Graphin/index.tsx
  src/components/OptionsPage/index.css
  src/components/OptionsPage/index.tsx
  src/manifest.json
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectNetwork.tsx
  src/pages/Content/content.styles.css
  src/utils/color.ts
  src/utils/number.ts
  src/utils/utils.ts
Labels: pull/approved

#123 fix: remove tabs
  src/manifest.json
  src/pages/Background/index.ts
Labels: kind/bug, pull/approved

#127 fix: cpu high load bug
  src/components/OptionsPage/index.tsx
Labels: kind/bug, pull/approved

#129 feat: add tooltip to options page
  package.json
  publish/update_information.json
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/OptionsPage/index.tsx
  src/mock/background.data.ts
Labels: pull/approved
