Repository hypertrons/hypertrons-crx, pull requests merged in 2021-09, with the labels that each got.

#213 fix: bug blocking build
  src/pages/Content/DeveloperNetwork.tsx
  src/pages/Content/ProjectNetwork.tsx
Labels: kind/bug, pull/approved

#180 fix the doc, when select the unzipped folder return err.
  INSTALLATION.md
  INSTALLATION.zh-CN.md
Labels: area/document, pull/approved

#221 feat: Add DynamicBar component.
  package.json
  src/components/DynamicBar/DynamicBar.tsx
  src/components/DynamicBar/PlayButton/PlayButton.tsx
Labels: pull/approved
