Repository hypertrons/hypertrons-crx, pull requests merged in 2021-03, with the labels that each got.

#48 feat: update hypertrons config file
  .github/hypertrons.json
  package-lock.json
Labels: pull/approved

#52 fix: adapt for new component DashboardService
  src/pages/Content/common/ConfigService.ts
  src/pages/Content/common/DashboardService.tsx
  src/pages/Content/components/Welcome/index.css
  src/pages/Content/components/Welcome/index.test.tsx
  src/pages/Content/components/Welcome/index.tsx
  src/pages/Content/github/index.ts
  src/pages/Content/index.ts
  yarn.lock
Labels: kind/bug

#57 fix: update contributing guide
  CONTRIBUTING.md
Labels: kind/bug, pull/approved

#58 feat: add ability for background tasks and local storage
  package.json
  src/manifest.json
  src/pages/Background/index.js
  src/pages/Background/index.ts
  src/pages/Content/index.ts
  src/pages/Options/Options.css
  src/pages/Options/Options.jsx
  src/pages/Options/index.jsx
  src/pages/Options/index.tsx
  src/pages/Popup/Popup.css
  src/pages/Popup/Popup.jsx
  src/pages/Popup/index.jsx
  src/pages/Popup/index.tsx
  src/utils/services.js
  src/utils/utils.ts
  webpack.config.js
Labels: pull/approved

#55 feat: add developer collabration network component
  src/pages/Content/components/DeveloperCollabrationNetwork/index.tsx
  src/pages/Content/components/DeveloperCollabrationNetwork/sample.data.ts
Labels: pull/approved

#63 feat: add support for i18n
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/manifest.json
  src/pages/Content/components/DeveloperCollabrationNetwork/index.tsx
  webpack.config.js
Labels: pull/approved

#64 Pr template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: pull/approved

#67 Pr template
  .github/pull_request_template.md
Labels: pull/approved

#66 feat: auto generate .crx pre-releases
  .github/workflows/build.yml
  .gitignore
  build.pem
  package.json
  webpack.config.js
  yarn.lock
Labels: pull/approved

#71 feat: add options page && popup page
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/OptionsPage/index.css
  src/components/OptionsPage/index.tsx
  src/components/PopupPage/index.css
  src/components/PopupPage/index.tsx
  src/manifest.json
  src/pages/Options/index.tsx
  src/pages/Popup/index.tsx
  src/utils/utils.ts
Labels: pull/approved

#72 fix: disable auto-build on pull-requests
  .github/workflows/build.yml
Labels: kind/bug, pull/approved

#69 feat: add perceptor tab
  package-lock.json
  package.json
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/pages/Content/common/DashboardService.tsx
  src/pages/Content/common/PageDetect.ts
  src/pages/Content/components/DeveloperCollabrationNetwork/index.css
  src/pages/Content/components/DeveloperCollabrationNetwork/index.tsx
  src/pages/Content/components/Network/ForceNetwork.tsx
  src/pages/Content/components/PerceptorLayout/index.tsx
  src/pages/Content/features/developer-network.tsx
  src/pages/Content/features/index.tsx
  src/pages/Content/features/perceptor-layout.tsx
  src/pages/Content/features/perceptor-tab.tsx
  src/pages/Content/features/project-network.tsx
  src/pages/Content/index.css
  src/pages/Content/index.ts
  src/pages/Content/mock/developer.data.ts
  src/pages/Content/mock/project.data.ts
Labels: pull/approved

#75 Refactor: move components folder
  src/components/Network/ForceNetwork.tsx
  src/components/PerceptorLayout/index.tsx
  src/pages/Content/common/ConfigService.ts
  src/pages/Content/common/PageDetect.ts
  src/pages/Content/config-service.ts
  src/pages/Content/features/developer-network.tsx
  src/pages/Content/features/perceptor-layout.tsx
  src/pages/Content/features/perceptor-tab.tsx
  src/pages/Content/features/project-network.tsx
  src/utils/utils.ts
Labels: kind/enhancement, pull/approved

#76 feat: introduce global settings api
  src/components/OptionsPage/index.tsx
  src/components/PopupPage/index.tsx
  src/utils/settings.ts
  src/utils/utils.ts
Labels: pull/approved

#80 refactor: refactor developer network
  src/_locales/en/messages.json
  src/_locales/zh_CN/messages.json
  src/components/Network/ForceNetwork.tsx
  src/components/OptionsPage/index.tsx
  src/mock/developer.data.ts
  src/mock/project.data.ts
  src/pages/Content/features/developer-network.css
  src/pages/Content/features/developer-network.tsx
  src/pages/Content/features/index.tsx
  src/pages/Content/features/perceptor-layout.tsx
  src/pages/Content/features/perceptor-tab.tsx
  src/pages/Content/features/project-network.css
  src/pages/Content/features/project-network.tsx
  src/pages/Content/mock/developer.data.ts
  src/pages/Content/mock/project.data.ts
  src/pages/Options/index.tsx
  src/utils/settings.ts
  src/utils/utils.ts
Labels: kind/enhancement, pull/approved
