Repository hypertrons/hypertrons-crx, pull requests merged in 2022-08, with the labels that each got.

#429 refactor: remove unnecessary injected script
  src/manifest.json
  src/pages/ContentScripts/index.ts
  src/pages/InjectedScripts/index.ts
  webpack.config.js
Labels: kind/enhancement, pull/approved

#397 refactor: new avc design
  src/Perceptor.tsx
  src/PerceptorBase.tsx
  src/anchors/DeveloperActInflTrendAnchor.tsx
  src/anchors/DeveloperNetworkAnchor.tsx
  src/anchors/HypertronsAnchor.tsx
  src/anchors/PerceptorLayoutAnchor.tsx
  src/anchors/PerceptorTabAnchor.tsx
  src/anchors/ProjectNetworkAnchor.tsx
  src/anchors/RepoActiInflTrendAnchor.tsx
  src/manifest.json
  src/pages/ContentScripts/index.css
  src/pages/ContentScripts/index.ts
  src/views/DeveloperActiInflTrendView/DeveloperActiInflTrendView.tsx
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
  src/views/HypertronsView/HypertronsView.tsx
  src/views/PerceptorLayoutView/PerceptorLayoutView.tsx
  src/views/ProjectNetworkView/ProjectNetworkView.tsx
  src/views/RepoActiInflTrendView/RepoActiInflTrendView.tsx
  src/views/TeachingBubbleWrapperView/TeachingBubbleWrapperView.tsx
  utils/server.js
  webpack.config.js
Labels: kind/enhancement, pull/approved

#437 docs: add node version requirement
  README.md
  README.zh-CN.md
  package.json
Labels: area/document, pull/approved

#438 Issue resolved for the width of the chart container
  src/components/Graph/Echarts/index.tsx
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
  src/views/ProjectNetworkView/ProjectNetworkView.tsx
Labels: pull/approved

#440 fix: failed to find insightsTab
  src/anchors/PerceptorLayoutAnchor.tsx
  src/anchors/PerceptorTabAnchor.tsx
Labels: kind/bug, pull/approved
