Repository hypertrons/hypertrons-crx, pull requests merged in 2022-06, with the labels that each got.

#356 Feature/328 added profile pic in contribution network
  .gitignore
  package.json
  src/components/Graph/Graph.tsx
  yarn.lock
Labels: pull/approved, kind/feature

#358 Feature/328 added profile picture in dev network and update readme
  README.md
  src/components/Graph/Graph.tsx
Labels: pull/approved, kind/feature

#366 Update README.md
  README.md
Labels: pull/approved

#379 chore: update new issues url
  CONTRIBUTING.md
  src/constant.ts
Labels: pull/approved

#352 ci: a new workflow to handle Hypercrx versions and automatic deploy
  .github/workflows/build.yml
  .github/workflows/pull_request_test_build.yml
  .github/workflows/release-deploy.yml
  .github/workflows/update-information.yml
  package.json
  scripts/bump-version.js
  scripts/deploy.js
  scripts/pre-commit.js
  scripts/utils.js
  yarn.lock
Labels: kind/enhancement, pull/approved
