Repository hypertrons/hypertrons-crx, pull requests merged in 2022-09, with the labels that each got.

#447 docs: added "hypercrx" pronounciation to README
  README.md
  README.zh-CN.md
Labels: area/document, pull/approved

#450 bug: fix auto reload on locales
  utils/server.js
Labels: kind/bug, pull/approved

#456 feat: click activity bar to view all issues and PRs in that month
  src/components/Bars/index.tsx
  src/views/RepoActiInflTrendView/RepoActiInflTrendView.tsx
Labels: pull/approved
