Repository hypertrons/hypertrons-crx, pull requests merged in 2022-10, with the labels that each got.

#464 fix: perceptor components cannot be disabled
  src/Perceptor.tsx
Labels: kind/bug, pull/approved

#462 refactor: remove antv related codes
  package.json
  src/anchors/DeveloperNetworkAnchor.tsx
  src/anchors/ProjectNetworkAnchor.tsx
  src/components/Graph/Graph.tsx
  src/components/Graph/Graphin/index.tsx
  src/global.d.ts
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
  src/pages/Options/Options.tsx
  src/utils/settings.ts
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
  src/views/ProjectNetworkView/ProjectNetworkView.tsx
  yarn.lock
Labels: kind/enhancement, pull/approved

#466 fix: use `query` to fiter events of Echarts
  src/components/Graph/Echarts/index.tsx
  src/components/Graph/Graph.tsx
Labels: kind/bug, pull/approved

#471 fix: public template is not regarded as public repo
  src/utils/utils.ts
Labels: kind/bug, pull/approved

#476 ci: auto mark issue reply status
  .github/workflows/issue-comment.yml
  .github/workflows/issue-open.yml
Labels: pull/approved

#477 fix: the width of tooltip is too small
  src/views/RepoDetailIssueView/IssueChart.tsx
  src/views/RepoDetailPRView/MergedLinesChart.tsx
  src/views/RepoDetailPRView/PRChart.tsx
  src/views/RepoDetailPRView/RepoDetailPRView.tsx
Labels: kind/bug

#482 fix: recenter the title of mergedline chart
  src/views/RepoDetailPRView/MergedLinesChart.tsx
Labels: pull/approved

#484 fix: modify the css class of the two network buttons in profile perceptor to avoid be truncated
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
Labels: kind/bug, pull/approved

#485 fix: avoid redundant renders
  src/anchors/DeveloperActInflTrendAnchor.tsx
  src/anchors/DeveloperNetworkAnchor.tsx
Labels: kind/bug, pull/approved

#486 docs: update pull_request_template.md
  .github/pull_request_template.md
Labels: area/document, pull/approved

#490 docs: update readme install
  README.md
Labels: area/document, pull/approved

#492 docs: update Chinese README
  README.zh-CN.md
Labels: area/document, pull/approved
