Repository hypertrons/hypertrons-crx, pull requests merged in 2022-11, with the labels that each got.

#501 style: change popups style by a designer's guidance
  README.md
  README.zh-CN.md
  src/anchors/RepoDetailForkAnchor.tsx
  src/anchors/RepoDetailIssueAnchor.tsx
  src/anchors/RepoDetailPRAnchor.tsx
  src/anchors/RepoDetailStarAnchor.tsx
  src/components/Bars/index.tsx
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
  src/pages/ContentScripts/index.scss
  src/views/RepoDetailForkView/ForkChart.tsx
  src/views/RepoDetailForkView/RepoDetailForkView.tsx
  src/views/RepoDetailIssueView/IssueChart.tsx
  src/views/RepoDetailIssueView/RepoDetailIssueView.tsx
  src/views/RepoDetailPRView/MergedLinesChart.tsx
  src/views/RepoDetailPRView/PRChart.tsx
  src/views/RepoDetailPRView/RepoDetailPRView.tsx
  src/views/RepoDetailStarView/RepoDetailStarView.tsx
  src/views/RepoDetailStarView/StarChart.tsx
  src/views/RepoHeaderLabelsView/ActivityChart.tsx
  src/views/RepoHeaderLabelsView/InfluenceChart.tsx
  src/views/RepoHeaderLabelsView/ParticipantChart.tsx
  src/views/RepoHeaderLabelsView/RepoHeaderLabelsView.tsx
Labels: pull/approved

#505 fix: repoLabel is not recognized right
  src/utils/utils.ts
Labels: kind/bug, pull/approved

#503 fix: bars of ActiInflTrend Chart not respond to click when language is English
  src/views/RepoActiInflTrendView/RepoActiInflTrendView.tsx
Labels: kind/bug, pull/approved

#511 style: slight change of UI
  src/anchors/RepoDetailForkAnchor.tsx
  src/anchors/RepoDetailIssueAnchor.tsx
  src/anchors/RepoDetailPRAnchor.tsx
  src/anchors/RepoDetailStarAnchor.tsx
  src/pages/ContentScripts/index.scss
  src/views/RepoHeaderLabelsView/RepoHeaderLabelsView.tsx
Labels: pull/approved

#514 style: add dark mode for hypertron command pop up window
  src/views/HypertronsView/HypertronsView.tsx
Labels: pull/approved

#518 fix: header labels cannot be triggered sometimes
  src/anchors/RepoHeaderLabelsAnchor.tsx
Labels: kind/bug, pull/approved

#521 docs: introduce OpenDigger in README
  README.md
  README.zh-CN.md
Labels: area/document, pull/approved

#522 refactor: use new API to refactor existing components
  src/api/developer.ts
  src/api/repo.ts
  src/components/Bars/index.tsx
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
  src/utils/data.ts
  src/views/DeveloperActiInflTrendView/DeveloperActiInflTrendView.tsx
  src/views/RepoActiInflTrendView/RepoActiInflTrendView.tsx
  src/views/RepoDetailForkView/RepoDetailForkView.tsx
  src/views/RepoDetailIssueView/IssueChart.tsx
  src/views/RepoDetailIssueView/RepoDetailIssueView.tsx
  src/views/RepoDetailPRView/MergedLinesChart.tsx
  src/views/RepoDetailPRView/PRChart.tsx
  src/views/RepoDetailPRView/RepoDetailPRView.tsx
  src/views/RepoDetailStarView/RepoDetailStarView.tsx
  src/views/RepoHeaderLabelsView/ActivityChart.tsx
  src/views/RepoHeaderLabelsView/InfluenceChart.tsx
  src/views/RepoHeaderLabelsView/RepoHeaderLabelsView.tsx
Labels: kind/enhancement, pull/approved

#524 feat: add issue and pr related interaction
  src/views/RepoDetailIssueView/IssueChart.tsx
  src/views/RepoDetailIssueView/RepoDetailIssueView.tsx
  src/views/RepoDetailPRView/PRChart.tsx
  src/views/RepoDetailPRView/RepoDetailPRView.tsx
Labels: pull/approved

#529 refactor: replace all occurrences of "Influence" with "OpenRank"
  README.md
  README.zh-CN.md
  src/anchors/DeveloperActORTrendAnchor.tsx
  src/anchors/RepoActORTrendAnchor.tsx
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
  src/pages/ContentScripts/index.ts
  src/views/DeveloperActORTrendView/DeveloperActORTrendView.tsx
  src/views/RepoActORTrendView/RepoActORTrendView.tsx
  src/views/RepoHeaderLabelsView/OpenRankChart.tsx
  src/views/RepoHeaderLabelsView/RepoHeaderLabelsView.tsx
Labels: kind/enhancement, pull/approved

#536 perf: debounce echartsInstance.resize() to avoid pages becoming slow when window being resized
  src/components/Graph/Echarts/index.tsx
  src/utils/utils.ts
Labels: pull/approved

#537 docs: Add OpenDigger badge.
  README.md
  README.zh-CN.md
Labels: area/document, pull/approved
