Repository hypertrons/hypertrons-crx, pull requests merged in 2022-12, with the labels that each got.

#542 refactor: add wrapper to handle date formatting so json update in OpenDigger will not break Hypercrx
  src/utils/data.ts
Labels: kind/enhancement, pull/approved

#544 fix: fatal date parse error
  src/utils/data.ts
Labels: kind/bug, pull/approved

#545 chore: remove the extra useless code
  src/utils/data.ts
Labels: pull/approved

#547 refactor: remove code to get a minimal Hypercrx so we can refactor it without too much burden
  package.json
  scripts/bump-version.cjs
  src/Perceptor.tsx
  src/anchors/HypertronsAnchor.tsx
  src/anchors/PerceptorTabAnchor.tsx
  src/api/developer.ts
  src/api/github.ts
  src/api/repo.ts
  src/components/DynamicRadar/ControlBar/ControlBar.tsx
  src/components/DynamicRadar/DynamicRadar.tsx
  src/components/DynamicRadar/Radar/Radar.tsx
  src/components/DynamicRadar/SimpleTable/SimpleTable.tsx
  src/mock/background.data.ts
  src/mock/developer.data.ts
  src/mock/repo.data.ts
  src/pages/Background/index.ts
  src/pages/ContentScripts/index.ts
  src/pages/Options/Options.tsx
  src/pages/Popup/Popup.css
  src/pages/Popup/Popup.tsx
  src/pages/Popup/index.css
  src/pages/Popup/index.jsx
  src/services/background.ts
  src/services/common.ts
  src/services/hypertrons.ts
  src/utils/metadata.ts
  src/utils/request.ts
  src/utils/settings.ts
  src/utils/utils.test.ts
  src/utils/utils.ts
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
  src/views/HypertronsView/HypertronsView.tsx
  src/views/TeachingBubbleWrapperView/TeachingBubbleWrapperView.tsx
  utils/env.js
  webpack.config.js
  yarn.lock
Labels: kind/enhancement
