Repository hypertrons/hypertrons-crx, pull requests merged in 2022-07, with the labels that each got.

#384 refactor: pure es6 import syntax
  .github/workflows/release-deploy.yml
  package.json
  scripts/bump-version.cjs
  scripts/deploy.js
  scripts/pre-commit.cjs
  scripts/pre-commit.js
  scripts/utils.cjs
  src/utils/request.ts
  utils/autoReloadClients/backgroundClient.js
  utils/build.js
  utils/crx-webpack-plugin/index.js
  utils/env.js
  utils/server.js
  webpack.config.js
  yarn.lock
Labels: kind/enhancement

#401 fix: using dark theme in day time or vice verse is not considered
  src/components/Graph/Graph.tsx
  src/pages/ContentScripts/DeveloperActiInflTrend.tsx
  src/pages/ContentScripts/RepoActiInflTrend.tsx
  src/utils/utils.ts
Labels: kind/bug

#396 fix: fatal issue 382
  src/manifest.json
  src/pages/Background/index.ts
  src/pages/ContentScripts/DeveloperActiInflTrend.tsx
  src/pages/ContentScripts/DeveloperNetwork.tsx
  src/pages/ContentScripts/PerceptorLayout.tsx
  src/pages/ContentScripts/ProjectNetwork.tsx
  src/pages/ContentScripts/index.ts
  src/pages/InjectedScripts/index.ts
  webpack.config.js
Labels: kind/bug, priority/high

#412 docs: fix broken images in README
  README.md
  README.zh-CN.md
Labels: area/document

#417 docs: removed link from opera icon in README
  README.md
  README.zh-CN.md
Labels: area/document, pull/approved

#421 community: invite @wxharry to be one of the Hypercrx maintainers 🎉
  .github/hypertrons.json
Labels: kind/community

#425 docs: fix broken image and change table style
  INSTALLATION.md
  INSTALLATION.zh-CN.md
  README.md
  README.zh-CN.md
Labels: area/document, pull/approved

#426 fix: add package cross-env
  package.json
  yarn.lock
Labels: kind/bug, pull/approved
