Repository hypertrons/hypertrons-crx, pull requests merged in 2023-05, with the labels that each got.

#659 refactor: reconstruct option management
  src/constant.ts
  src/feature-manager.ts
  src/global.d.ts
  src/options-storage.ts
  src/pages/ContentScripts/features/developer-activity-openrank-trends/view.tsx
  src/pages/ContentScripts/features/developer-networks/view.tsx
  src/pages/ContentScripts/features/oss-gpt/view.tsx
  src/pages/ContentScripts/features/repo-activity-openrank-trends/view.tsx
  src/pages/ContentScripts/features/repo-fork-tooltip/view.tsx
  src/pages/ContentScripts/features/repo-header-labels/view.tsx
  src/pages/ContentScripts/features/repo-issue-tooltip/view.tsx
  src/pages/ContentScripts/features/repo-networks/view.tsx
  src/pages/ContentScripts/features/repo-pr-tooltip/view.tsx
  src/pages/ContentScripts/features/repo-star-tooltip/view.tsx
  src/pages/Options/Options.tsx
  src/pages/Options/index.jsx
  src/pages/Popup/Popup.tsx
  src/pages/Popup/index.jsx
  src/utils/settings.ts
  src/utils/utils.ts
  utils/features-loader.cjs
  webpack.config.js
  yarn.lock
Labels: kind/enhancement

#674 docs: revise grammatical errors and typos of MD
  CONTRIBUTING.md
  INSTALLATION.md
  INSTALLATION.zh-CN.md
  README.md
Labels: kind/bug, area/document, pull/approved

#679 docs: grammatical errors of Perceptor tab and readme.md
  README.md
  src/locales/en/messages.json
Labels: kind/bug, area/document, pull/approved

#683 fix: repositioning the fork chart
  src/pages/ContentScripts/features/repo-fork-tooltip/index.tsx
Labels: kind/bug, pull/approved

#685 fix: truncate redundant profile information
  src/helpers/get-developer-info.ts
Labels: kind/bug, pull/approved
