Repository hypertrons/hypertrons-crx, pull requests merged in 2023-03, with the labels that each got.

#596 refactor: DeveloperActORTrend -> developer-activity-openrank-trends
  src/anchors/DeveloperActORTrendAnchor.tsx
  src/helpers/get-developer-info.ts
  src/pages/ContentScripts/features/developer-activity-openrank-trends/index.tsx
  src/pages/ContentScripts/features/developer-activity-openrank-trends/view.tsx
  src/pages/ContentScripts/index.ts
Labels: kind/enhancement, pull/approved

#589 refactor: add perceptor tab and layout & relevant feature injection
  src/feature-manager.ts
  src/helpers/should-feature-run.ts
  src/pages/ContentScripts/features/perceptor-layout/index.tsx
  src/pages/ContentScripts/features/perceptor-layout/view.tsx
  src/pages/ContentScripts/features/perceptor-tab/icon-svg-path.ts
  src/pages/ContentScripts/features/perceptor-tab/index.tsx
  src/pages/ContentScripts/index.ts
Labels: kind/enhancement, kind/feature

#598 refactor: RepoDetailIssue -> repo-issue-tooltip
  .github/workflows/issue-comment.yml
  src/anchors/PerceptorLayoutAnchor.tsx
  src/anchors/PerceptorTabAnchor.tsx
  src/anchors/RepoDetailIssueAnchor.tsx
  src/pages/ContentScripts/features/repo-fork-tooltip/ForkChart.tsx
  src/pages/ContentScripts/features/repo-issue-tooltip/IssueChart.tsx
  src/pages/ContentScripts/features/repo-issue-tooltip/index.tsx
  src/pages/ContentScripts/features/repo-issue-tooltip/view.tsx
  src/pages/ContentScripts/index.ts
  src/views/PerceptorLayoutView/PerceptorLayoutView.tsx
Labels: kind/enhancement

#600 refactor: RepoDetailPR -> repo-pr-tooltip
  src/anchors/RepoDetailPRAnchor.tsx
  src/pages/ContentScripts/features/repo-pr-tooltip/MergedLinesChart.tsx
  src/pages/ContentScripts/features/repo-pr-tooltip/PRChart.tsx
  src/pages/ContentScripts/features/repo-pr-tooltip/index.tsx
  src/pages/ContentScripts/features/repo-pr-tooltip/view.tsx
  src/pages/ContentScripts/index.ts
  src/utils/settings.ts
Labels: kind/enhancement

#602 refactor: RepoHeaderLabels -> repo-header-labels
  src/anchors/RepoHeaderLabelsAnchor.tsx
  src/pages/ContentScripts/features/repo-header-labels/ActivityChart.tsx
  src/pages/ContentScripts/features/repo-header-labels/OpenRankChart.tsx
  src/pages/ContentScripts/features/repo-header-labels/ParticipantChart.tsx
  src/pages/ContentScripts/features/repo-header-labels/base64.ts
  src/pages/ContentScripts/features/repo-header-labels/index.tsx
  src/pages/ContentScripts/features/repo-header-labels/view.tsx
  src/pages/ContentScripts/index.ts
Labels: kind/enhancement

#605 fix: false positve case of isPerceptor
  src/utils/utils.ts
Labels: kind/bug, pull/approved

#607 fix: the network will crash if no edge provided
  src/components/Graph.tsx
Labels: kind/bug, pull/approved

#606 feat: chat widget for DocsGPT
  package.json
  src/anchors/DocsGPTChatWidget.tsx
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
  src/pages/ContentScripts/index.ts
  src/pages/Options/Options.tsx
  src/utils/settings.ts
  src/views/DocsGPTChatWidget/index.tsx
  src/views/DocsGPTChatWidget/rcw.scss
  src/views/DocsGPTChatWidget/service.ts
  yarn.lock
Labels: area/document, pull/approved

#612 style: disable chat widget badge (the red unread bubble)
  src/views/DocsGPTChatWidget/index.tsx
Labels: pull/approved

#617 style: add avatar for OSS-GPT chat bot
  src/views/DocsGPTChatWidget/index.tsx
  src/views/DocsGPTChatWidget/rcw.scss
Labels: pull/approved

#621 style: modify the drop-down box of network views
  src/locales/en/messages.json
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
  src/views/ProjectNetworkView/ProjectNetworkView.tsx
Labels: pull/approved

#623 feat: add i18n support for OSS-GPT chat widget
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
  src/views/DocsGPTChatWidget/index.tsx
Labels: pull/approved

#633 docs: update Chinese and English README for OSS-GPT chat widget
  README.md
  README.zh-CN.md
Labels: area/document, pull/approved

#635 fix: all zeros problem
  README.md
  README.zh-CN.md
  src/utils/data.ts
Labels: kind/bug, kind/question
