Repository hypertrons/hypertrons-crx, pull requests merged in 2023-02, with the labels that each got.

#556 ci: manually input version number to release new version
  .github/release.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
  CHANGELOG.md
  package.json
  scripts/bump-version.cjs
Labels: kind/enhancement, pull/approved

#570 community: invite @lhbvvvvv to be one of the Hypercrx maintainers
  .github/hypertrons.json
Labels: kind/community, pull/approved

#575 refactor: RepoDetailFork -> features/repo-fork-tooltip
  src/anchors/RepoDetailForkAnchor.tsx
  src/feature-manager.ts
  src/helpers/should-feature-run.ts
  src/helpers/sleep.ts
  src/pages/ContentScripts/features/repo-activity-openrank-trends/index.tsx
  src/pages/ContentScripts/features/repo-fork-tooltip/ForkChart.tsx
  src/pages/ContentScripts/features/repo-fork-tooltip/index.tsx
  src/pages/ContentScripts/features/repo-fork-tooltip/view.tsx
  src/pages/ContentScripts/index.ts
  src/utils/utils.ts
  src/views/RepoDetailForkView/RepoDetailForkView.tsx
Labels: kind/enhancement, kind/feature

#568 fix: PR chart won't show if one of metric files doesn't exist
  src/api/common.ts
  src/api/developer.ts
  src/api/repo.ts
  src/components/ExceptionPage/ErrorPage.tsx
  src/utils/data.ts
  src/utils/request.ts
  src/utils/utils.ts
  src/views/DeveloperActORTrendView/DeveloperActORTrendView.tsx
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
  src/views/ProjectNetworkView/ProjectNetworkView.tsx
  src/views/RepoActORTrendView/RepoActORTrendView.tsx
  src/views/RepoDetailForkView/RepoDetailForkView.tsx
  src/views/RepoDetailIssueView/IssueChart.tsx
  src/views/RepoDetailIssueView/RepoDetailIssueView.tsx
  src/views/RepoDetailPRView/MergedLinesChart.tsx
  src/views/RepoDetailPRView/PRChart.tsx
  src/views/RepoDetailPRView/RepoDetailPRView.tsx
  src/views/RepoDetailStarView/RepoDetailStarView.tsx
  src/views/RepoHeaderLabelsView/RepoHeaderLabelsView.tsx
Labels: kind/bug, pull/approved

#585 fix: some charts are broken because of new data fields like `yyyy-mm-raw`
  src/utils/data.ts
Labels: kind/bug, pull/approved

#587 fix: newestMonth should not be the last month in data files
  src/utils/data.ts
Labels: kind/bug, pull/approved
