Repository hypertrons/hypertrons-crx, pull requests merged in 2023-04, with the labels that each got.

#637 refactor: ProjectNetwork -> repo-networks
  src/anchors/ProjectNetworkAnchor.tsx
  src/feature-manager.ts
  src/pages/ContentScripts/features/perceptor-layout/index.tsx
  src/pages/ContentScripts/features/perceptor-layout/view.tsx
  src/pages/ContentScripts/features/repo-networks/DataNotFound.tsx
  src/pages/ContentScripts/features/repo-networks/index.tsx
  src/pages/ContentScripts/features/repo-networks/view.tsx
  src/pages/ContentScripts/index.ts
Labels: kind/enhancement

#638 refactor: DeveloperNetwork -> developer-networks
  .github/workflows/issue-open.yml
  package.json
  src/Perceptor.tsx
  src/PerceptorBase.tsx
  src/anchors/DeveloperNetworkAnchor.tsx
  src/components/ExceptionPage/ErrorMessageBar.tsx
  src/components/ExceptionPage/ErrorPage.tsx
  src/pages/ContentScripts/features/developer-networks/icon-svg-path.ts
  src/pages/ContentScripts/features/developer-networks/index.tsx
  src/pages/ContentScripts/features/developer-networks/react-modal.scss
  src/pages/ContentScripts/features/developer-networks/view.tsx
  src/pages/ContentScripts/features/repo-networks/view.tsx
  src/pages/ContentScripts/index.ts
  src/utils/logger.tsx
  src/utils/utils.ts
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
  yarn.lock
Labels: kind/enhancement

#639 refactor: oss-gpt with the new loading mechanism
  README.md
  README.zh-CN.md
  package.json
  publish/update_information.json
  src/locales/en/messages.json
  src/locales/zh_CN/messages.json
  src/mock/background.data.ts
  src/pages/ContentScripts/features/oss-gpt/index.tsx
  src/pages/ContentScripts/features/oss-gpt/rcw.scss
  src/pages/ContentScripts/features/oss-gpt/service.ts
  src/pages/ContentScripts/features/oss-gpt/view.tsx
  src/pages/ContentScripts/features/perceptor-tab/index.tsx
  src/pages/ContentScripts/index.ts
  yarn.lock
Labels: kind/enhancement

#642 fix: wrongly highlight tab
  src/pages/ContentScripts/features/perceptor-tab/index.tsx
Labels: kind/bug, pull/approved

#648 fix: fixed collpase issues (#647)
  src/pages/ContentScripts/index.scss
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
Labels: kind/bug, pull/approved

#650 fix: resolve aligment issues (#649)
  src/pages/ContentScripts/index.scss
  src/views/DeveloperNetworkView/DeveloperNetworkView.tsx
Labels: kind/bug, pull/approved

#656 fix: resolve alignment issues (#649)
  src/pages/ContentScripts/features/developer-networks/view.tsx
  src/pages/ContentScripts/features/perceptor-tab/index.tsx
  src/pages/ContentScripts/index.scss
Labels: kind/bug

#658 fix: abnormal-width on text select
  src/pages/ContentScripts/features/oss-gpt/view.tsx
Labels: kind/bug
